format = "$directory$git_branch $git_status$character"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "normal"
format = "[$path]($style)"

[git_branch]
symbol = ""
style = "normal"
format = " ($branch)"

[git_status]
style = "normal"
format = "($all_status )"
ahead = "↑"
behind = "↓"
diverged = "↕"
modified = "*"
untracked = ""
staged = ""
deleted = ""
renamed = ""
conflicted = "!"

[python]
disabled = true

[cmd_duration]
disabled = true

[character]
success_symbol = "❯"
error_symbol = "[❯](red)"
